package es.ucm.jadedrools
 
import es.ucm.jadedrools.mapa.Mapa;
import es.ucm.jadedrools.mapa.TipoCasilla;
import es.ucm.jadedrools.mapa.Casilla;
import es.ucm.jadedrools.agentes.transportista.Transportista;

rule "movimientoTransportista"
    when
        $trans: Transportista()
    then
        double mejorDistancia = 10000.0;
        int mejorNextX = $trans.getX();
		int mejorNextY = $trans.getY();
        
    	for (int i = -1; i <= 1; i++){
			for (int j = -1; j <= 1; j++){
				
				int a = Math.abs(($trans.getX() + i) - $trans.getX_mov());
            	int b = Math.abs(($trans.getY() + j) - $trans.getY_mov());
            	
            	//la distancia entre 2 puntos (entre el minero1 y el mineral)
            	double distancia = Math.sqrt(a*a + b*b);
            	
            	if (distancia < mejorDistancia){
            		mejorNextX = $trans.getX() + i;
            		mejorNextY = $trans.getY() + j;
            		mejorDistancia = distancia;
            	}
			}
		}
		
		$trans.setX(mejorNextX);
		$trans.setY(mejorNextY);
end